Wallet id setup
docknetwork/dock-app pull request #118
Opened 2022-02-17 18:10 UTC by Riffat-Shahzad

@maycon-mello please check this PR, Units tests are failing but i think these are not because of my changes. Please have a look.

2022-02-21 16:45 UTC, mike-parkhill requested changes

2022-02-21 16:45 UTC, mike-parkhill commented on src/features/accounts/AccountsScreen.js
> +              testID="CreateNewAccount"
it's a minor thing but you're mixing the naming style. Some up above use underscores (receive_tokens_btn), others us camelCase (tokenReceive) and here it's Pascal case (CreateNewAccount). Can we pick one style and stick with it throughout?

2022-02-21 16:45 UTC, mike-parkhill commented on src/features/wallet/CreateWalletScreen.js
> +          accessibilityLabel="import_existing"
previously you were setting `accessibilityID` but now it's `accessibilityLabel`. Why the change? What's the difference?

2022-02-21 16:45 UTC, mike-parkhill commented on ios/Podfile.lock
> +COCOAPODS: 1.11.2
is this upgrade intentional?

2022-02-21 16:45 UTC, mike-parkhill commented on ios/Podfile.lock
> +  FBReactNativeSpec: 90dc7e6dd04f23a173ef8d5a29535c695400ae7c
Does changing this ID affect anything?

2022-02-21 16:47 UTC, Riffat-Shahzad commented on ios/Podfile.lock
> +COCOAPODS: 1.11.2
I have not done this, Maycon needs to check, how this happened.

2022-02-21 16:47 UTC, Riffat-Shahzad commented on src/features/wallet/CreateWalletScreen.js
> +          accessibilityLabel="import_existing"
Combination of accessibilityLabel makes it visible

2022-02-21 16:55 UTC, Riffat-Shahzad commented on ios/Podfile.lock
> +  FBReactNativeSpec: 90dc7e6dd04f23a173ef8d5a29535c695400ae7c
some update has done this. I have done it explicitly. Reverting it

2022-02-25 18:20 UTC, maycon-mello commented on ios/Podfile.lock
> +COCOAPODS: 1.11.2
This is auto generated lock file, should be fine

2022-03-02 14:15 UTC, maycon-mello commented
@mike-parkhill @ShahzadRiffat I did a small refactor adding a utility function to inject testIDs and accessibilityLabel properties. Also fixed some linting issues

2022-03-02 15:40 UTC, mike-parkhill commented
> @mike-parkhill @ShahzadRiffat I did a small refactor adding a utility function to inject testIDs and accessibilityLabel properties. Also fixed some linting issues

That helper looks useful. Can we get it pulled through all the other changes? I'm still seeing a mix of `accessibilityLabel` and `accessibilityID` being used as well as the inconsistent naming that I mentioned earlier.

2022-03-02 17:38 UTC, maycon-mello commented
> > @mike-parkhill @ShahzadRiffat I did a small refactor adding a utility function to inject testIDs and accessibilityLabel properties. Also fixed some linting issues
> 
> That helper looks useful. Can we get it pulled through all the other changes? I'm still seeing a mix of `accessibilityLabel` and `accessibilityID` being used as well as the inconsistent naming that I mentioned earlier.

accessibilityID looks wrong, I can fix that. Will also check to make sure we are using the helper in other places

2022-03-02 18:22 UTC, maycon-mello commented
@mike-parkhill I've updated all the test IDs, it should be using the same naming convention now.

2022-03-02 18:57 UTC, mike-parkhill approved these changes

2022-03-02 19:01 UTC, merged