Fix Dock 2007
docknetwork/dock-app pull request #119
Opened 2022-03-01 13:07 UTC by osinakayah

Problem: When apply button is clicked, onNetworkChange is called, onNetworkChange is a promise and it takes a while to get resolved, this is the reason the modal does not close immediately.

Solution: Instead of waiting for the promise to get resolved before closing the modal, the modal is closed immediately then the network change process is then triggered next.

Suggestions: Include a toast to notify the user when the network change has been completed (When the promise gets resolved)

Link: https://dock-team.atlassian.net/browse/DCK-2007

2022-03-01 14:39 UTC, mike-parkhill commented on src/features/dev-settings/DevSettingsScreen.js
> +                onNetworkChange(networkId).then(() => {})
what happens if the network change fails? Should we show a toast or something letting them know it failed?

2022-03-01 14:43 UTC, mike-parkhill requested changes
Question about how we should handle errors in the network change and it looks like a couple of very minor linting issues.

2022-03-01 15:30 UTC, osinakayah commented on src/features/dev-settings/DevSettingsScreen.js
> +                onNetworkChange(networkId).then(() => {})
Yes, I think we do that too

2022-03-02 09:59 UTC, osinakayah commented
@mike-parkhill 
I think we can include a toast message when it is successful and when it fails.
I have pushed another commit for that.

2022-03-02 14:19 UTC, maycon-mello commented
Linting issues were fixed in the dev branch and I did a rebase on this one. CI should pass now

2022-03-02 15:42 UTC, mike-parkhill commented on src/features/dev-settings/DevSettingsScreen.js
> +                    showToast({
would it be useful to log the error? @maycon-mello what scenarios would cause it to fail?

2022-03-02 18:00 UTC, maycon-mello commented on src/features/dev-settings/DevSettingsScreen.js
> +                    showToast({
The substrate server could be offline

2022-03-02 18:01 UTC, maycon-mello commented on src/features/dev-settings/DevSettingsScreen.js
> +                    showToast({
Logging it will send the error to sentry as well, not sure if that's useful

2022-03-02 18:23 UTC, mike-parkhill commented on src/features/dev-settings/DevSettingsScreen.js
> +                    showToast({
Hmm, I don't want to flood Sentry with noise, but if we're seeing consistent issues it would be nice to know why too. If there are known errors we don't need to know about then can we filter them out, but for unknowns log them maybe?

Can we check the quality of the Internet connection if we get an error? Probably wouldn't do it in this ticket, but maybe add it later.

2022-03-03 10:23 UTC, hodlEngineer commented on src/features/dev-settings/DevSettingsScreen.js
> +                    showToast({
@mike-parkhill 
Yes, I think it is possible to check the internet speed.
https://github.com/TSjianjiao/react-native-network-speed
https://github.com/AsbarAli/react-native-network-bandwith-speed

2022-03-03 10:25 UTC, osinakayah commented on src/features/dev-settings/DevSettingsScreen.js
> +                    showToast({
@mike-parkhill 
I think it is possible to check the internet speed.
https://github.com/TSjianjiao/react-native-network-speed
https://github.com/AsbarAli/react-native-network-bandwith-speed

2022-03-03 15:48 UTC, mike-parkhill commented on src/features/dev-settings/DevSettingsScreen.js
> +                    showToast({
and what about filtering out "accepted" errors but allowing others to log?

2022-03-07 20:16 UTC, osinakayah commented on src/features/dev-settings/DevSettingsScreen.js
> +                    showToast({
Maybe we can skip logging errors related to network failures, since most likely they won't be caused by errors in our code but by external factors such as timeout, no network or service not available.

2022-03-07 21:12 UTC, mike-parkhill commented on src/features/dev-settings/DevSettingsScreen.js
> +                    showToast({
Yeah, I guess that makes sense. At some point we may need to manage network connections more intelligently so we can give better messages to the users, but for now we can probably ignore them but should probably track other errors.

2022-03-09 15:14 UTC, osinakayah commented on src/features/dev-settings/DevSettingsScreen.js
> +                    showToast({
@mike-parkhill 
I did a little bit of testing/debugging and no exception is thrown substrate server url is wrong or when there is no network.  It just doesn't do anything.

2022-03-09 15:16 UTC, mike-parkhill commented on src/features/dev-settings/DevSettingsScreen.js
> +                    showToast({
Ok, so does that mean we're not going to change anything here then?

2022-03-09 19:25 UTC, osinakayah commented on src/features/dev-settings/DevSettingsScreen.js
> +                    showToast({
Yes, we do not.

2022-03-09 19:38 UTC, mike-parkhill approved these changes

2022-03-09 19:50 UTC, merged