Chore/build 101
docknetwork/dock-app pull request #134
Opened 2022-03-21 14:11 UTC by maycon-mello

2022-03-21 17:45 UTC, mike-parkhill requested changes
minor linting issue

2022-03-22 01:14 UTC, mike-parkhill commented on src/features/accounts/AccountDetailsScreen.js
> +  console.log('return to account details', accountId);
did you intentionally leave this in?

2022-03-22 01:16 UTC, mike-parkhill approved these changes

2022-03-22 12:39 UTC, maycon-mello commented on src/features/accounts/AccountDetailsScreen.js
> +  console.log('return to account details', accountId);
needs to be removed, will push a separate pr for that

2022-03-22 12:39 UTC, merged