Dcka 838 did managament
docknetwork/dock-app pull request #303
Opened 2022-07-13 18:01 UTC by osinakayah

2022-07-14 19:29 UTC, mike-parkhill commented on src/features/didManagement/CreateNewDIDScreen.js
> +            <Select
does this need a test ID?

2022-07-14 19:30 UTC, mike-parkhill commented on src/features/didManagement/CreateNewDIDScreen.test.js
> +  it('should render correctly with hmm', () => {
`with hmm`? 😕

2022-07-14 19:33 UTC, mike-parkhill commented on src/features/didManagement/DIDListScreen.js
> +              <DIDListItem
do these need testIds so they can be easily selected?

2022-07-14 19:37 UTC, mike-parkhill commented on src/features/didManagement/components/SingleDIDOptionsModal.js
> +          // {
is this placeholder for when you implement edit?

2022-07-14 19:46 UTC, mike-parkhill commented on src/features/didManagement/didManagment-slice.js
> +  if (newDidParams.didType === 'didkey') {
I generally dislike `if` trees like this. They're not bad when there's only two options, but get unwieldy very quickly as you add more. A pattern I like is to register factory functions in a dictionary using the type as a key.  This function would then just be a dictionary lookup.

    const didFactories = { 
         'diddock': createDockDID, 
         'didkey', createKeyDID
    };

Probably means refactoring to pass newDidParams into all the factory functions but that's probably okay.

2022-07-14 19:48 UTC, mike-parkhill commented on src/features/didManagement/didManagment-slice.js
> +export const createNewDID = async newDidParams => {
are there tests that can be written to make sure you get the right DID being generated? 

Not sure how we'd manage the did:dock blockchain access.

2022-07-14 19:49 UTC, mike-parkhill commented on src/locales/languages/en.json
> +    "did_creation_error": "Oops, an error occurred creating DID",
not sure about the `Oops`. Don't think we use that casual tone elsewhere.

2022-07-14 21:26 UTC, osinakayah commented on src/features/didManagement/didManagment-slice.js
> +export const createNewDID = async newDidParams => {
> Not sure how we'd manage the did:dock blockchain access.
Yes, I will include the test for did:key for now.

2022-07-19 14:07 UTC, mike-parkhill commented on src/core/redux-store.js
> +  // middleware.push(logger);
did you intend to commit this?

2022-07-19 14:14 UTC, mike-parkhill commented on src/features/didManagement/didHooks.js
> +      name: didName,
how about trim here too? Or is there somewhere on the form that we can trim once so we don't have to always check it?

2022-07-19 14:14 UTC, mike-parkhill commented on src/features/didManagement/didHooks.js
> +    console.log(didResolutionDocuments.length, 'didResolutionDocuments.length');
did you intend to leave this?

2022-07-19 14:16 UTC, mike-parkhill requested changes
Some linting errors too.

2022-07-20 14:44 UTC, mike-parkhill commented on src/features/didManagement/didHooks.js
> +      } catch (e) {}
should we be doing something with this error?

2022-07-20 15:33 UTC, osinakayah commented on src/features/didManagement/didHooks.js
> +        translate('didManagement.error_keypair_type', {
Hmm, true. 
We have a helper function that reads the actual error message, displays them and post them to sentry, let me it instead.

2022-07-20 18:13 UTC, mike-parkhill commented on src/locales/languages/en.json
> +    "error_keypair_type": "%{keypairType} keypair type  is not supported.",
here's the other half of that double space 😄

2022-07-20 20:57 UTC, mike-parkhill approved these changes

2022-07-21 00:39 UTC, merged