Dcka 828 did management
docknetwork/dock-app pull request #306
Opened 2022-07-29 07:58 UTC by osinakayah

2022-07-29 16:37 UTC, maycon-mello commented on src/features/didManagement/ExportDIDScreen.js
>                  placeholder="Password"
Shouldn't we use locales here?

2022-07-29 16:37 UTC, maycon-mello commented on src/features/didManagement/ExportDIDScreen.js
>                  placeholder="Confirm password"
We could use locales here

2022-07-29 16:38 UTC, maycon-mello commented on src/features/didManagement/ExportDIDScreen.js
> +          updatedForm.lengthValidation = value.length >= 8;
can we test this? maybe move this code to a separate function

2022-07-29 16:39 UTC, maycon-mello commented on test/testSetup.js
> +  // return {
can we remove this code?

2022-07-29 16:40 UTC, maycon-mello requested changes
left some comments

2022-07-29 18:50 UTC, osinakayah commented on test/testSetup.js
> +  // return {
It is needed for the mock to work. I wanted to mock the "open" function in the react-native-share library.

2022-08-01 19:15 UTC, maycon-mello approved these changes

2022-08-01 19:15 UTC, merged