Credential status
docknetwork/dock-app pull request #386
Opened 2022-10-26 18:13 UTC by osinakayah

2022-10-27 15:05 UTC, maycon-mello requested changes
question about duplicated code

2022-10-27 15:05 UTC, maycon-mello commented on src/features/credentials/CredentialsScreen.js
> +            <NBox
Can we avoid the duplicated NBox and styling? perhaps something like this:
```
<NBox
    mr={1}
    style={{
      width: 12,
      height: 12,
      borderRadius: 6,
      backgroundColor: isCredentialValid(credential) ? Theme.colors.circleChecke : Theme.colors.error
    }}
  />
`

2022-10-27 20:16 UTC, mike-parkhill commented on src/features/credentials/components/CredentialStatus.test.js
> +  it('should render correctly', () => {
should probably have a snapshot for each of Verified, Invalid and Expired (and potentially Revoked if we can identify it)

2022-10-27 20:16 UTC, mike-parkhill commented on src/features/credentials/components/CredentialStatus.js
> +    switch (status) {
are we able to differentiate Revoked from Invalid?

2022-10-27 20:20 UTC, mike-parkhill commented on src/features/credentials/credentials.js
> +    ? isInThePast(new Date(credential.expirationDate))
what happens if `credential.expirationDate` doesn't represent a valid date/time? e.g. it's just text or some other object structure?

2022-10-28 18:00 UTC, mike-parkhill commented on src/assets/icons/index.js
> +import RevokeIcon from './revoke.svg';
nitpick: should probably be `RevokedIcon`

2022-10-28 18:01 UTC, mike-parkhill commented on src/features/credentials/hooks/credentialHooks.js
> +    console.log(credential, 'credential');
is this log still needed?

2022-10-28 18:02 UTC, mike-parkhill commented on src/features/credentials/hooks/credentialHooks.test.js
> +  it('get credential status', async () => {});
were you intending to add something here?

2022-10-28 18:35 UTC, osinakayah commented on src/features/credentials/hooks/credentialHooks.js
> +    console.log(credential, 'credential');
No, it I will remove it in the next commit

2022-10-28 18:35 UTC, osinakayah commented on src/features/credentials/hooks/credentialHooks.test.js
> +  it('get credential status', async () => {});
Yes, I am working on the unit test now.

2022-10-31 18:55 UTC, mike-parkhill approved these changes

2022-10-31 19:55 UTC, maycon-mello approved these changes

2022-10-31 19:55 UTC, merged